In [1]:
import pandas as pd

edos_dataset = "../Dataset/Original/edos_labelled_aggregated.csv"
edos_df = pd.read_csv(edos_dataset)
train_df = edos_df[edos_df['split'] == 'train']
val_df = edos_df[edos_df['split'] == 'dev']
test_df = edos_df[edos_df['split'] == 'test']

print("Train set size:", len(train_df))
print("Validation set size:", len(val_df))
print("Test set size:", len(test_df))

edos_df.head()

Train set size: 14000
Validation set size: 2000
Test set size: 4000

,rewire_id,text,label_sexist,label_category,label_vector,split
0,sexism2022_english-9609,"In Nigeria, if you rape a woman, the men rape ...",not sexist,none,none,dev
1,sexism2022_english-16993,"Then, she's a keeper. 😉",not sexist,none,none,train
2,sexism2022_english-13149,This is like the Metallica video where the poo...,not sexist,none,none,train
3,sexism2022_english-13021,woman?,not sexist,none,none,train
4,sexism2022_english-966,I bet she wished she had a gun,not sexist,none,none,dev

In [2]:
test_df['label_vector'].value_counts()

label_vector
none                                                               3030
2.1 descriptive attacks                                             205
2.2 aggressive and emotive attacks                                  192
3.1 casual use of gendered slurs, profanities, and insults          182
3.2 immutable gender differences and gender stereotypes             119
4.2 supporting systemic discrimination against women as a group      73
1.2 incitement and encouragement of harm                             73
2.3 dehumanising attacks & overt sexual objectification              57
4.1 supporting mistreatment of individual women                      21
3.3 backhanded gendered compliments                                  18
1.1 threats of harm                                                  16
3.4 condescending explanations or unwelcome advice                   14
Name: count, dtype: int64

In [6]:
conan_dataset = "../Dataset/Original/Multitarget-CONAN.json"

df = pd.read_json(conan_dataset, orient="index")
df.head()

,HATE_SPEECH,COUNTER_NARRATIVE,TARGET,VERSION
0,Maybe the UN could talk to those asian and afr...,"You're right, ocean pollution is one of the ma...",other,V1
1,‘Juice (Jews) are worse that nukes.’ Caption t...,You'd rather be nuked then?,JEWS,V1
2,Foreigners on UK benefits leaps 41% in 5 years...,You seem to be worried about government expend...,MIGRANTS,V1
3,"Jews cannot be patriots, since their allegianc...",You can have parents and grandparents born els...,JEWS,V1
4,"Israel, Zionism and Jewish Supremacist control...",Wouldn't you say its colonialism from many dif...,JEWS,V1

In [10]:
# get only WOMEN
df_women = df[df["TARGET"] == "WOMEN"]
df_women.head()

,HATE_SPEECH,COUNTER_NARRATIVE,TARGET,VERSION
5,"Women are basically childlike, they remain thi...",Would you say the same thing to the women who ...,WOMEN,V1
8,Who the fuck are you? We are gutful sick of Va...,Without women there would be no men.,WOMEN,V1
9,"Women are basically childlike, they remain thi...",WIthout softeness and emotions there would jus...,WOMEN,V1
10,Who the fuck are you? We are gutful sick of Va...,What makes you think that women are jealous of...,WOMEN,V1
13,We began to break down when we allowed women t...,"Who is 'we', surely it was men and women worki...",WOMEN,V1